### ISSUE TITLE
求个使用方法的readme 

### ISSUE THREAD

**Issue by Paul-Qu** [Acer611/douyin_video#1]
求个使用方法的readme，多谢大佬

**Comment by Jake-Qu** [comment]
不知道怎么找到关键字去替换，并且下载特定用户的视频

**Comment by Jake-Qu** [comment]
sec_uid怎么得到呢？

**Comment by Acer611** [comment]
你去你要下载的抖音号的主页，右上角分享--&gt;复制链接--&gt;粘贴到浏览器中


浏览器的地址栏中能找到你想要的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Acer611/douyin_video"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 下午5:04
收件人:&nbsp;"Acer611/douyin_video"<douyin_video@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Acer611/douyin_video] 求个使用方法的readme  (#1)





 
sec_uid怎么得到呢？

**Comment by Paul-Qu** [comment]
> 你去你要下载的抖音号的主页，右上角分享--&gt;复制链接--&gt;粘贴到浏览器中 浏览器的地址栏中能找到你想要的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Acer611/douyin_video" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月4日(星期二) 下午5:04 收件人:&nbsp;"Acer611/douyin_video"<douyin_video@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [Acer611/douyin_video] 求个使用方法的readme (#1) sec_uid怎么得到呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢
